object Android {
    private const val coreVersion = "1.12.0"
    private const val lifecycleRuntimeVersion = "2.7.0"
    private const val appcompatVersion = "1.6.1"
    private const val androidxStartupVersionVersion = "1.1.1"
    private const val androidxActivityVersion = "1.8.2"
    private const val androidxTracingVersion = "1.2.0"
    private const val androidxExifinterfaceVersion = "1.3.7"
    private const val androidxLifecycleServiceVersion = "2.7.0"
    private const val androidxAnimationVersion = "1.3.3"
    private const val androidToolsVersion = "2.0.4"
    const val androidCore = "androidx.core:core-ktx:$coreVersion"
    const val lifecycleRuntime = "androidx.lifecycle:lifecycle-runtime-ktx:$lifecycleRuntimeVersion"
    const val appcompat = "androidx.appcompat:appcompat:$appcompatVersion"
    const val androidxActivity = "androidx.activity:activity:$androidxActivityVersion"
    const val androidxStartup = "androidx.startup:startup-runtime:$androidxStartupVersionVersion"
    const val androidxTracing = "androidx.tracing:tracing-ktx:$androidxTracingVersion"
    const val androidxTracingLifecycleService = "androidx.lifecycle:lifecycle-service:$androidxLifecycleServiceVersion"
    const val androidxExifinterface = "androidx.exifinterface:exifinterface:$androidxExifinterfaceVersion"
    const val androidToolsDesugar= "com.android.tools:desugar_jdk_libs_nio:$androidToolsVersion"
    const val animation= "androidx.compose.animation:animation:$androidxAnimationVersion"

}